// AUTO-GENERATED by scripts/buildGalleryManifest.mjs — do not edit by hand
export const generatedGalleries = [
  {
    "slug": "portraits",
    "title": "Portraits",
    "date": "2025-08-16",
    "location": "—",
    "category": "people",
    "hero": {
      "src": "/photos/people/portraits/hero.jpg",
      "alt": "Portraits — hero"
    },
    "images": [
      {
        "src": "/photos/people/portraits/DSC00076.jpg",
        "alt": "Portraits: DSC00076",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC00090.jpg",
        "alt": "Portraits: DSC00090",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC00091.jpg",
        "alt": "Portraits: DSC00091",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC00161.jpg",
        "alt": "Portraits: DSC00161",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC00783.jpg",
        "alt": "Portraits: DSC00783",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01275.jpg",
        "alt": "Portraits: DSC01275",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01276.jpg",
        "alt": "Portraits: DSC01276",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01514.jpg",
        "alt": "Portraits: DSC01514",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01515.jpg",
        "alt": "Portraits: DSC01515",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01516.jpg",
        "alt": "Portraits: DSC01516",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01650.jpg",
        "alt": "Portraits: DSC01650",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01690.jpg",
        "alt": "Portraits: DSC01690",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01695.jpg",
        "alt": "Portraits: DSC01695",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01751.jpg",
        "alt": "Portraits: DSC01751",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01763.jpg",
        "alt": "Portraits: DSC01763",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01783.jpg",
        "alt": "Portraits: DSC01783",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01805.jpg",
        "alt": "Portraits: DSC01805",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01840.jpg",
        "alt": "Portraits: DSC01840",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01850.jpg",
        "alt": "Portraits: DSC01850",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01851.jpg",
        "alt": "Portraits: DSC01851",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01879.jpg",
        "alt": "Portraits: DSC01879",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01893.jpg",
        "alt": "Portraits: DSC01893",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC01937.jpg",
        "alt": "Portraits: DSC01937",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC02116.jpg",
        "alt": "Portraits: DSC02116",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/DSC02167.jpg",
        "alt": "Portraits: DSC02167",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/IMG_5108.jpg",
        "alt": "Portraits: IMG 5108",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/people/portraits/IMG_8406.jpg",
        "alt": "Portraits: IMG 8406",
        "meta": {
          "camera": "",
          "settings": ""
        }
      }
    ]
  },
  {
    "slug": "city-coastal-views",
    "title": "City Coastal Views",
    "date": "2025-08-16",
    "location": "—",
    "category": "landscapes",
    "hero": {
      "src": "/photos/landscapes/city-coastal-views/hero.jpg",
      "alt": "City Coastal Views — hero"
    },
    "images": [
      {
        "src": "/photos/landscapes/city-coastal-views/DSC00376.jpg",
        "alt": "City Coastal Views: DSC00376",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/DSC00685.jpg",
        "alt": "City Coastal Views: DSC00685",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/DSC01260.jpg",
        "alt": "City Coastal Views: DSC01260",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/DSC01343.jpg",
        "alt": "City Coastal Views: DSC01343",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/DSC01364.jpg",
        "alt": "City Coastal Views: DSC01364",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/DSC01365.jpg",
        "alt": "City Coastal Views: DSC01365",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/DSC01366.jpg",
        "alt": "City Coastal Views: DSC01366",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/DSC01796.jpg",
        "alt": "City Coastal Views: DSC01796",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/IMG_6705.jpg",
        "alt": "City Coastal Views: IMG 6705",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/IMG_7099.jpg",
        "alt": "City Coastal Views: IMG 7099",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/IMG_8307.jpg",
        "alt": "City Coastal Views: IMG 8307",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/IMG_8377.jpg",
        "alt": "City Coastal Views: IMG 8377",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/IMG_8996.jpg",
        "alt": "City Coastal Views: IMG 8996",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/landscapes/city-coastal-views/IMG_8997.jpg",
        "alt": "City Coastal Views: IMG 8997",
        "meta": {
          "camera": "",
          "settings": ""
        }
      }
    ]
  },
  {
    "slug": "pets",
    "title": "Pets",
    "date": "2025-08-16",
    "location": "—",
    "category": "animals",
    "hero": {
      "src": "/photos/animals/pets/hero.jpg",
      "alt": "Pets — hero"
    },
    "images": [
      {
        "src": "/photos/animals/pets/DSC00075.jpg",
        "alt": "Pets: DSC00075",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/DSC00299.jpg",
        "alt": "Pets: DSC00299",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/DSC00302.jpg",
        "alt": "Pets: DSC00302",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/DSC00303.jpg",
        "alt": "Pets: DSC00303",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/DSC00304.jpg",
        "alt": "Pets: DSC00304",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/DSC00400.jpg",
        "alt": "Pets: DSC00400",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/DSC01564.jpg",
        "alt": "Pets: DSC01564",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/DSC01568.jpg",
        "alt": "Pets: DSC01568",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/IMG_5848.jpg",
        "alt": "Pets: IMG 5848",
        "meta": {
          "camera": "",
          "settings": ""
        }
      },
      {
        "src": "/photos/animals/pets/IMG_5849.jpg",
        "alt": "Pets: IMG 5849",
        "meta": {
          "camera": "",
          "settings": ""
        }
      }
    ]
  }
];
